#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

pattern='^(🎉|✨|🐛|♻️|📝|🎨|✅|🔧|⚡|🚀|🔥|🗃️|🔒|⬆️|🚑|🧾) (feat|fix|docs|style|refactor|test|chore|perf|build|ci)(\([a-zA-Z0-9_-]+\))?: .+'

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo ""
  echo "❌ Mensagem de commit inválida!"
  echo ""
  echo "Use o padrão:"
  echo "emoji tipo(escopo): descrição"
  echo ""
  echo "Exemplos válidos:"
  echo "🎉 chore(project): adiciona versão inicial do projeto"
  echo "✨ feat(produto): adiciona cadastro com leitor"
  echo "🐛 fix(venda): corrige cálculo do subtotal"
  echo "🧾 feat(comprovante): adiciona cupom não fiscal"
  echo ""
  exit 1
fi